# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
    - 'v*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Build Packages   
        run: pnpm build
      
      - name: Copy Files
        run: cp README.md packages/ && cp LICENSE packages/

      - name: Publish package to NPM 📦
        run: cd packages/ && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
